return {}
-- return {
-- 	{
-- 		"yetone/avante.nvim",
-- 		event = "VeryLazy",
-- 		lazy = false,
-- 		version = false, -- set this if you want to always pull the latest change
-- 		opts = {
-- 			provider = "claude-code",
-- 			-- auto_suggestions_provider = "claude",
-- 			-- providers = {
-- 			--   claude = {
-- 			--     endpoint = "https://api.anthropic.com",
-- 			--     model = "claude-3-5-sonnet-20241022",
-- 			--     extra_request_body = {
-- 			--       max_tokens = 4096,
-- 			--       temperature = 0,
-- 			--     },
-- 			--   },
-- 			-- },
-- 			-- behaviour = {
-- 			--   auto_suggestions = false, -- Experimental stage
-- 			--   auto_set_highlight_group = true,
-- 			--   auto_set_keymaps = true,
-- 			--   auto_apply_diff_after_generation = false,
-- 			--   support_paste_from_clipboard = false,
-- 			-- },
-- 			-- mappings = {
-- 			--   --- @class AvanteConflictMappings
-- 			--   diff = {
-- 			--     ours = "co",
-- 			--     theirs = "ct",
-- 			--     all_theirs = "ca",
-- 			--     both = "cb",
-- 			--     cursor = "cc",
-- 			--     next = "]x",
-- 			--     prev = "[x",
-- 			--   },
-- 			--   suggestion = {
-- 			--     accept = "<M-l>",
-- 			--     next = "<M-]>",
-- 			--     prev = "<M-[>",
-- 			--     dismiss = "<C-]>",
-- 			--   },
-- 			--   jump = {
-- 			--     next = "]]",
-- 			--     prev = "[[",
-- 			--   },
-- 			-- },
-- 			-- hints = { enabled = true },
-- 			-- windows = {
-- 			--   position = "right", -- the position of the sidebar
-- 			--   wrap = true, -- similar to vim.o.wrap
-- 			--   width = 30, -- default % based on available width
-- 			--   sidebar_header = {
-- 			--     align = "center", -- left, center, right for title
-- 			--     rounded = true,
-- 			--   },
-- 			-- },
-- 		},
-- 		-- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
-- 		build = "make",
-- 		-- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
-- 		dependencies = {
-- 			"stevearc/dressing.nvim",
-- 			"nvim-lua/plenary.nvim",
-- 			"MunifTanjim/nui.nvim",
-- 			--- The below dependencies are optional,
-- 			"nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
-- 			"zbirenbaum/copilot.lua", -- for providers='copilot'
-- 			{
-- 				-- support for image pasting
-- 				"HakonHarnes/img-clip.nvim",
-- 				event = "VeryLazy",
-- 				opts = {
-- 					-- recommended settings
-- 					default = {
-- 						embed_image_as_base64 = false,
-- 						prompt_for_file_name = false,
-- 						drag_and_drop = {
-- 							insert_mode = true,
-- 						},
-- 						-- required for Windows users
-- 						use_absolute_path = true,
-- 					},
-- 				},
-- 			},
-- 			{
-- 				-- Make sure to set this up properly if you have lazy=true
-- 				"MeanderingProgrammer/render-markdown.nvim",
-- 				opts = {
-- 					file_types = { "markdown", "Avante" },
-- 				},
-- 				ft = { "markdown", "Avante" },
-- 			},
-- 		},
-- 		keys = {
-- 			{ "<C-i>", "<cmd>AvanteAsk<cr>", mode = { "n", "v" }, desc = "Avante Agent Mode" },
-- 			{ "<C-k>", "<cmd>AvanteEdit<cr>", mode = { "n", "v" }, desc = "Avante Inline Edit" },
-- 		},
-- 	},
-- }

